lib/viablehire_web/router.ex
defmodule ViablehireWeb.Router do
  use ViablehireWeb, :router

  pipeline :auth do
    plug ViablehireWeb.Plugs.RequireAuth
  end

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
    plug ViablehireWeb.Plugs.SetUser
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/auth", ViablehireWeb do
    pipe_through :browser
    get "/logout", AuthController, :logout
    get "/:provider", AuthController, :request
    get "/:provider/callback", AuthController, :callback
    post "/:provider/callback", AuthController, :callback
  end

  scope "/users", ViablehireWeb do
    pipe_through [:browser, :auth]
    resources "/", UserController, except: [:index, :new, :create]
  end

  scope "/jobs", ViablehireWeb do
    pipe_through [:browser, :auth]
    resources "/", JobController
  end

  scope "/bids", ViablehireWeb do
    pipe_through [:browser, :auth]
    resources "/", BidController, except: [:new]
    get "/new/:id", BidController, :new
    get "/job/:id", BidController, :index_for_job
    get "/accept/:id", BidController, :accept_bid
    get "/unaccept/:id", BidController, :unaccept_bid
  end

  scope "/", ViablehireWeb do
    pipe_through :browser # Use the default browser stack
    get "/", PageController, :index
  end

  scope "/dashboard", ViablehireWeb do
    pipe_through [:browser, :auth]
    get "/", PageController, :dashboard
  end

  # Other scopes may use custom stacks.
  # scope "/api", ViablehireWeb do
  #   pipe_through :api
  # end
end

lib/viablehire_web/views/layout_view.ex
defmodule ViablehireWeb.LayoutView do
  use ViablehireWeb, :view
end

lib/viablehire_web/templates/layout/_alerts.html.eex
<%= if get_flash(@conn, :info) do %>
<p class="alert alert-secondary" role="alert"><%= get_flash(@conn, :info) %></p>
<% end %>
<%= if get_flash(@conn, :error) do %>
<p class="alert alert-danger" role="alert"><%= get_flash(@conn, :error) %></p>
<% end %>

lib/viablehire_web/templates/layout/_navigation.html.eex
<header class="header">
    <nav class="navbar navbar-expand-md navbar-dark bg-dark">
        <%= link "Aelper", to: page_path(@conn, :dashboard), class: "navbar-brand font-weight-bold" %>

        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse ml-auto" id="navbarSupportedContent">
            <%= if @conn.assigns.user do %>
                <span class="navbar-text ml-auto badge badge-light text-dark">Welcome <%= @conn.assigns.user.nickname %></span>
            <% end %>
            <ul class="navbar-nav ml-auto">
                <%= if @conn.assigns.user do %>
                    <li class="nav-item">
                        <a class="nav-link" href=<%= job_path(@conn, :index) %>>Available Jobs</a></li>
                    <li class="nav-item">
                        <a class="nav-link" href=<%= page_path(@conn, :dashboard) %>>Dashboard</a></li>
                    <li class="nav-item">
                        <a class="nav-link" href=<%= job_path(@conn, :new) %>>Post Job</a></li>
                    <li class="nav-item">
                        <a class="nav-link" href=<%= auth_path(@conn, :logout) %>>Logout</a></li>

                <% else %>
                        <li class="nav-item">
                            <a class="nav-link" href=<%= auth_path(@conn, :request, "auth0") %>>Login/Register</a></li>
                <% end %>
            </ul>
        </div>
    </nav>
</header>

lib/viablehire_web/templates/layout/app.html.eex
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <meta name="description" content="">
        <meta name="author" content="">

        <title>Hello Viablehire!</title>
        <link rel="stylesheet" href="<%= static_path(@conn, "/css/app.css") %>">
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
        <link rel="stylesheet" href="https://code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
        <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.2.0/css/all.css" integrity="sha384-hWVjflwFxL6sNzntih27bfxkr27PmbbK/iSvJ+a4+0owXq79v+lsFkW54bOGbiDQ" crossorigin="anonymous">    </head>

    <body>
        <div class="container-fluid">
            <%= render "_navigation.html", conn: @conn %>

            <%= render "_alerts.html", conn: @conn %>

            <main role="main">
                <%= render @view_module, @view_template, assigns %>
            </main>
        </div> <!-- /container -->
        <script
            src="https://code.jquery.com/jquery-3.3.1.min.js"
            integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8="
            crossorigin="anonymous"></script>
        <script
            src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"
            integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q"
            crossorigin="anonymous"></script>
        <script
            src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"
            integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl"
            crossorigin="anonymous"></script>
        <script
            src="https://code.jquery.com/ui/1.12.1/jquery-ui.min.js"
            integrity="sha256-VazP97ZCwtekAsvgPBSUwPFKdrwD3unUfSGVYrahUqU="
            crossorigin="anonymous"></script>
        <script src="<%= static_path(@conn, "/js/app.js") %>"></script>
        <%= render_existing @view_module, "scripts.html", assigns %>
    </body>
</html>